// Día de la documentación: 05/09/2023
//  *
//  * Descripción del archivo "store-flag.d.ts":
//  * Este archivo es un archivo de declaración TypeScript que define la característica "store" en Quasar.
//  * Declara la existencia de la característica "store" en el objeto "QuasarFeatureFlags" y la establece en "true".
//  * Esta característica se utiliza para habilitar o deshabilitar funcionalidades relacionadas con el almacenamiento de datos en Quasar.
//  * La inclusión de este archivo de declaración asegura que TypeScript reconozca esta característica y proporcione soporte de tipo adecuado.
/* eslint-disable */
// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import "quasar/dist/types/feature-flag";

declare module "quasar/dist/types/feature-flag" {
  interface QuasarFeatureFlags {
    store: true;
  }
}
